name: flutter_getx_template
description: Boilarplate template of Flutter GetX.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: '2.8.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  get: ^4.5.1
  flutter_svg: ^0.22.0
  dio: ^4.0.4
  shared_preferences: ^2.0.10
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
#  intl: 0.18.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  animations: ^2.0.2
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1
  font_awesome_flutter: ^9.2.0
  fluttertoast: ^8.0.8
  country_picker: ^2.0.19
  dropdown_button2: ^1.9.4
  carousel_slider: ^4.2.1
  readmore: ^2.1.0
  flutter_staggered_grid_view: ^0.6.2
#  flutter_staggered_grid_view: ^0.3.3
  video_player: ^2.5.2
#  video_player: ^2.1.15
  chewie: 1.4.0
  scroll_snap_list: ^0.9.1
#  dotted_border: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  analyzer: any
  dart_code_metrics: any
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/launcher_icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/videos/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
